language: node_js

node_js:
  - "6.9.5"

before_install:
  - pip install --user codecov

script:
  -  npm run cover

after_success:
  - codecov --file coverage/lcov.info --disable search
  - bash <(curl -s https://codecov.io/bash)
